### ISSUE TITLE
Auth token in .npmrc?

### ISSUE THREAD

**Issue by TomGranot** [Bogidon/dotfiles#1]
So, does this auth token actually work?
I didn't check, but might be a good idea to kill it.
https://github.com/Bogidon/dotfiles/blob/master/npm/.npmrc#L3

**Comment by Bogidon** [comment]
Thank you! Cleaned it up :)
Silly npm.

**Comment by TomGranot** [comment]
Well...
https://github.com/Bogidon/dotfiles/blob/948589c818785a3748a2f2a5eb2afcfbc903f652/npm/.npmrc#L3

Still in the history. Revoke it too? Somebody somewhere is scraping for those.

**Comment by TomGranot** [comment]
Ah, interesting, seems like GitHub caught on to it after I copy-pasted here. Or was it you just a second ago?

**Comment by TomGranot** [comment]
It also goes back, it seems:

https://github.com/Bogidon/dotfiles/blob/8c8cffb43d999c64cf76b4594d3ec734b2b03062/npm/.npmrc#L3

**Comment by Bogidon** [comment]
Twas I and maybe the GitHub cache I imagine. Thanks for your help!
